CREATE TABLE IF NOT EXISTS `damages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identy` LONGTEXT NOT NULL,
  `data` LONGTEXT NOT NULL,
  `canzirh` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;